server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,image/jpeg

screencast:
  output:
    imageCompression: 20 #Level for compression. 0 is the lowest compression, 100 the highest. Only works with JPG output type
    refreshIntervalMillis: 100
  mouse: #Config for the mouspointer display
    draw: true #Defines if the pointer should be shown or not. Allowed values: true (Show courser), false (Do not show courser)
    width: 7 #Width of the oval displaying the cursor in pixel
    height: 7 #Height of the oval displaying the cursor in pixel
    borderColor: "000000" #HEX color code for the courser border (outer 1px of the cursor)
    fillColor: "FF0000" #HEX color code for the cursor fill